version: '3.9'

services:
  m1:
    image: nginx:1.22.1
    volumes:
      # - ./lab4-ui:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8080:80
    networks:
      - farmazone
  m2:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./photos:/lab3-hotel/zdjecia
    networks:
      - farmazone

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    networks:
      - farmazone


  frontend:
    image: nginx:1.22.1
    volumes:
      - ./lab4-ui:/usr/share/nginx/html
    networks:
      - farmazone

networks:
  farmazone: